### ISSUE TITLE
change borderRadius

### ISSUE THREAD

**Issue by MahdiPishguy** [truthmast/bottom_sheet_bar#2]
how can we change `borderRadius` when achieve top of screen animation ?

**Comment by truthmast** [comment]
You can attach a listener to `BottomSheetBarController()`

In a `StatefulWidget`:
```dart
final _controller = BottomSheetBarController();
double _radius = 12.0

@override
void initState() {
  _controller.addListener(() {
    if(_controller.isExpanded) {
      setState(() => _radius = 0.0);
    }
  });
  super.initState();
}
```

```dart
@override
Widget build(BuildContext context) => BottomSheetBar(
      controller: _controller,
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(_radius),
        topRight: Radius.circular(_radius),
      ),
      expandedBuilder: (scrollController) => null, // TODO
      collapsed: null, // TODO
      body: null, // TODO
    )
```

I would like to add support for animating border-radius (and color as well) to provide this functionality out-of-the-box. Maybe some extra properties to configure animation end values in the expanded state:
- `expandedColor`
- `expandedBorderRadius`

**Comment by truthmast** [comment]
Added `borderRadiusExpanded` in version `1.0.2+6`

**Comment by MahdiPishguy** [comment]
> 
> 
> Added `borderRadiusExpanded` in version `1.0.2+6`

can be change when we dragging the sheet?

**Comment by truthmast** [comment]
It will animate between `borderRadius` and `borderRadiusExpanded` as you drag.

For example, `borderRadius = 32.0, borderRadiusExpanded = 0.0`:
![border_radius](https://user-images.githubusercontent.com/1178412/96378880-f2dd4300-1143-11eb-8b76-eb013c8c3f2f.gif)

**Comment by MahdiPishguy** [comment]
@truthmast thanks a lot,
